/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.view;

import com.controller.InvoiceActionListener;
import com.controller.SelectTabel;
import com.model.InvocieLine;
import com.model.InvoiceHeader;
import com.model.InvoiceHeaderTabelModel;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 *
 * @author ICON
 */
public class InvoiceFram extends javax.swing.JFrame {

    /**
     * Creates new form InvoiceFram
     */
    public InvoiceFram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        HeaderT = new javax.swing.JTable();
        invoicename = new javax.swing.JLabel();
        invoicedate = new javax.swing.JLabel();
        customername = new javax.swing.JLabel();
        invoicetotal = new javax.swing.JLabel();
        CreatInvoic = new javax.swing.JButton();
        Deleteinvoice = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        LineT = new javax.swing.JTable();
        Deleteline = new javax.swing.JButton();
        Creatline = new javax.swing.JButton();
        numinvoice = new javax.swing.JLabel();
        datainvoice = new javax.swing.JLabel();
        custname = new javax.swing.JLabel();
        totalline = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        LoadMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        HeaderT.getSelectionModel().addListSelectionListener(selectTabel);
        jScrollPane1.setViewportView(HeaderT);

        invoicename.setText("Invoice num");

        invoicedate.setText("Invoice Date");

        customername.setText("Customer Name");

        invoicetotal.setText("Invoice total");

        CreatInvoic.setText("New Invoice");
        CreatInvoic.addActionListener(actionListener);

        Deleteinvoice.setText("Delete Invoice");
        Deleteinvoice.addActionListener(actionListener);
        Deleteinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteinvoiceActionPerformed(evt);
            }
        });

        LineT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(LineT);

        Deleteline.setText("Delete Line");
        Deleteline.addActionListener(actionListener);
        Deleteline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletelineActionPerformed(evt);
            }
        });

        Creatline.setText("New Line");
        Creatline.addActionListener(actionListener);

        jMenu1.setText("File");

        LoadMenuItem.setText("Load Files");
        LoadMenuItem.addActionListener(actionListener);
        LoadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(LoadMenuItem);

        saveMenuItem.setText("Save Files");
        saveMenuItem.setToolTipText("");
        saveMenuItem.addActionListener(actionListener);
        jMenu1.add(saveMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CreatInvoic)
                        .addGap(39, 39, 39)
                        .addComponent(Deleteinvoice)
                        .addGap(93, 93, 93)
                        .addComponent(Creatline)
                        .addGap(53, 53, 53)
                        .addComponent(Deleteline))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customername)
                                    .addComponent(invoicedate)
                                    .addComponent(invoicename)
                                    .addComponent(invoicetotal))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalline)
                                    .addComponent(custname)
                                    .addComponent(datainvoice)
                                    .addComponent(numinvoice)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numinvoice)
                        .addGap(7, 7, 7)
                        .addComponent(invoicename)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoicedate)
                            .addComponent(datainvoice))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(customername)
                            .addComponent(custname))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalline)
                            .addComponent(invoicetotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deleteinvoice)
                    .addComponent(CreatInvoic)
                    .addComponent(Creatline)
                    .addComponent(Deleteline))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoadMenuItemActionPerformed

    private void DeleteinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteinvoiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteinvoiceActionPerformed

    private void DeletelineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletelineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeletelineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InvoiceFram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InvoiceFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatInvoic;
    private javax.swing.JButton Creatline;
    private javax.swing.JButton Deleteinvoice;
    private javax.swing.JButton Deleteline;
    private javax.swing.JTable HeaderT;
    private javax.swing.JTable LineT;
    private javax.swing.JMenuItem LoadMenuItem;
    private javax.swing.JLabel custname;
    private javax.swing.JLabel customername;
    private javax.swing.JLabel datainvoice;
    private javax.swing.JLabel invoicedate;
    private javax.swing.JLabel invoicename;
    private javax.swing.JLabel invoicetotal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel numinvoice;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JLabel totalline;
    // End of variables declaration//GEN-END:variables
private InvoiceActionListener actionListener=new InvoiceActionListener(this);
private ArrayList<InvoiceHeader> invoiceArray;
private ArrayList<InvocieLine> invoiceLines;
private InvoiceHeaderTabelModel headerTabelModel;
 public static SimpleDateFormat dateFormat=new SimpleDateFormat("dd-MM-yyyy");
 private SelectTabel selectTabel = new SelectTabel(this);

    public ArrayList<InvocieLine> getInvoiceLines() {
        return invoiceLines;
    }

    public void setInvoiceLines(ArrayList<InvocieLine> invoiceLines) {
        this.invoiceLines = invoiceLines;
    }
 

    public void setInvoiceArray(ArrayList<InvoiceHeader> invoiceArray) {
        this.invoiceArray = invoiceArray;
    }

    public ArrayList<InvoiceHeader> getInvoiceArray() {
        return invoiceArray;
    }
    
    public InvoiceHeader getInvObject(int code){
        for (InvoiceHeader inv : invoiceArray ){
            if(inv.getNum()== code){
                return inv;
            }
        }
        return null;
    }

    public InvoiceHeaderTabelModel getHeaderTabelModel() {
        return headerTabelModel;
    }

    public void setHeaderTabelModel(InvoiceHeaderTabelModel headerTabelModel) {
        this.headerTabelModel = headerTabelModel;
    }

    public JTable getHeaderT() {
        return HeaderT;
    }

    public JTable getLineT() {
        return LineT;
       
    }

    public JLabel getCustomername() {
        return customername;
    }

    public JLabel getInvoicedate() {
        return invoicedate;
    }

    public JLabel getInvoicename() {
        return invoicename;
    }

    public JLabel getInvoicetotal() {
        return invoicetotal;
    }

    public InvoiceActionListener getActionListener() {
        return actionListener;
    }

    }
